#!/usr/bin/env bash

export TERM="xterm-256color"

export EDITOR=nvim

# Enable vi mode
bindkey -v

# Reduce delay switching modes in vi mode
export KEYTIMEOUT=1

# fzf shell integration (Ctrl-R history, Ctrl-T files, Alt-C cd)
source <(fzf --zsh) 2>/dev/null

# zoxide - smart directory jumping (use 'z' instead of 'cd')
eval "$(zoxide init zsh)" 2>/dev/null

# zsh-autosuggestions (installed via Homebrew)
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
