#!/usr/bin/env bash

get_os() {
  # Detect the platform (similar to $OSTYPE)
  OS="`uname`"
  case $OS in
    'Linux')
      OS='linux'
      ;;
    'FreeBSD')
      OS='freebsd'
      ;;
    'WindowsNT')
      OS='windows'
      ;;
    'Darwin') 
      OS='macos'
      ;;
    'SunOS')
      OS='solaris'
      ;;
    'AIX') ;;
    *) ;;
  esac

  echo $OS
}
