#!/usr/bin/env bash

function ensure() {
    if ! hash "$1" > /dev/null 2>&1; then
        echo "Command not found: $1. Aborting..."
        exit 1
    else
      echo "$1 already installed"
    fi
}
