# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

# Enable command auto-correction.
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git vi-mode django mosh zsh-syntax-highlighting)

DISABLE_UPDATE_PROMPT=true
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh

# pure
fpath+=("$HOME/.zsh/pure")
autoload -U promptinit; promptinit
prompt pure

# Path changes
export PATH=${PATH}:~/.composer/vendor/bin
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"

# Terminal settings
export TERM="xterm-256color"

# Enable vi mode
bindkey -v

# Reduce delay switching modes in vi mode
export KEYTIMEOUT=1

# Register in zle
zle -N zle-keymap-select

# Add fnm (faster node manager)
eval "$(fnm env)"

# Include Z
[ -s "/opt/z/z.sh" ] && \. "/opt/z/z.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -f ~/.zshrc-local ] && source ~/.zshrc-local
[ -f ~/.zaliases ] && source ~/.zaliases
